name: Testing

on:
  push:


env:
  PROJECT_IMAGE_NAME: "ghcr.io/asim3/${{ github.event.repository.name }}"


jobs:
  docker_test:
    runs-on: ubuntu-latest
    name: Test on Docker
    steps:
      - uses: actions/checkout@v4

      - name: Copy Tests Env File
        run: cp ./src/.env.example ./src/.env

      - name: Build Docker Image
        run: >
          docker image build --no-cache
          -t ${PROJECT_IMAGE_NAME}:tests
          -f ./deploy/Dockerfile . ;

      - name: Run All Tests
        run: >
          docker container run --rm
          ${PROJECT_IMAGE_NAME}:tests
          'php artisan key:generate && php artisan test'
