version: "3.8"

services:
  db-mysql:
    image: mysql:lts-oraclelinux9
    environment:
      TZ: Asia/Riyadh
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --password=root  status"]
      start_period: 30s
      interval: 30s
      timeout: 3s
      retries: 1
    volumes:
      - db_data:/var/lib/mysql


  migrate-laravel: 
    build:
      context: .
    restart: on-failure
    depends_on:
      db-mysql:
        condition: service_healthy
    environment:
      TZ: Asia/Riyadh
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "php artisan migrate --force"


  app:
    build:
      context: .
    depends_on:
      migrate-laravel:
        condition: service_completed_successfully
    environment:
      TZ: Asia/Riyadh
    ports:
      - "8000:8000"


  adminer:
    image: adminer:4-standalone
    depends_on:
      migrate-laravel:
        condition: service_completed_successfully
    environment:
      TZ: Asia/Riyadh
      ADMINER_DEFAULT_SERVER: db-mysql
    ports:
      - 8080:8080

volumes:
  db_data:
