version: "3.8"

services:
  db-mysql:
    image: mysql:lts-oraclelinux9
    environment:
      TZ: Asia/Riyadh
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --password=root  status"]
      start_period: 30s
      interval: 30s
      timeout: 3s
      retries: 1
    volumes:
      - db_data:/var/lib/mysql

  setup-laravel: 
    image: composer:2.7.7
    user: "1000:1000"
    restart: on-failure
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "cd /laravel-src \
          && composer install \
          && if [ ! -f .env ]; then \
              cp .env.example .env && php artisan key:generate --ansi; \
              sed -i -e 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/'  ./.env; \
              sed -i -e 's/# DB_HOST=127.0.0.1/DB_HOST=db-mysql/'      ./.env; \
              sed -i -e 's/# DB_PORT=3306/DB_PORT=3306/'               ./.env; \
              sed -i -e 's/# DB_DATABASE=laravel/DB_DATABASE=laravel/' ./.env; \
              sed -i -e 's/# DB_USERNAME=root/DB_USERNAME=admin/'      ./.env; \
              sed -i -e 's/# DB_PASSWORD=/DB_PASSWORD=admin/'          ./.env; \
             fi; \
        "
    volumes:
      - "./src:/laravel-src"

  migrate-laravel: 
    build:
      context: .
    restart: on-failure
    depends_on:
      setup-laravel:
        condition: service_completed_successfully
      db-mysql:
        condition: service_healthy
    environment:
      TZ: Asia/Riyadh
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "cd /laravel-src \
          && php artisan vendor:publish --tag=laravel-assets --ansi --force \
          && php artisan migrate \
        "
    volumes:
      - "./src:/laravel-src"

  app:
    build:
      context: .
    depends_on:
      migrate-laravel:
        condition: service_completed_successfully
    environment:
      TZ: Asia/Riyadh
    ports:
      - "8000:8000"
    volumes:
      - "./src:/home/d_user/laravel-src"

  adminer:
    image: adminer:4-standalone
    depends_on:
      migrate-laravel:
        condition: service_completed_successfully
    environment:
      TZ: Asia/Riyadh
      ADMINER_DEFAULT_SERVER: db-mysql
    ports:
      - 8080:8080

volumes:
  db_data:
