name: Testing

on:
  push:
    branches:
      - main
      - dockerfile

jobs:
  docker_test:
    runs-on: ubuntu-latest
    name: Test on Docker
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker image build -t init/create-laravel-project:latest init

      - name: Debug 1
        run: ls -al ./ && ls -al ./.github/workflows && id -u && id -g

      - name: Run create laravel project
        run: docker run --rm -u $(id -u):$(id -g) -v '.:/repo' init/create-laravel-project:latest


      - name: Debug
        run: ls -al ./ && ls -al ./.github/workflows && ls -al ./src
